[project]
name = "codexaid"
version = "0.1.0"
description = "Code codex aid ai. "
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "mcp[cli]>=1.9.1",
    "pymilvus>=2.5.10",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
]
